export default () => {
  //
  const randomColorGenerator = (brightness) => {
    // Six levels of brightness from 0 to 5, 0 being the darkest
    const rgb = [Math.random() * 256, Math.random() * 256, Math.random() * 256];
    const mix = [brightness * 51, brightness * 51, brightness * 51]; //51 => 255/5
    const mixedrgb = [
      rgb[0] + mix[0],
      rgb[1] + mix[1],
      rgb[2] + mix[2],
    ].map((x) => Math.round(x / 2.0));
    return "rgba(" + mixedrgb.join(",") + ", 0.8)";
  };
  const NbDataMortaAn = document.getElementById("NbDataMortaAnGraph");
  const NbDataMortaAnChart = new Chart(NbDataMortaAn, {
    type: "bar",
    data: {
      labels: [
        2004,
        2005,
        2006,
        2007,
        2008,
        2009,
        2010,
        2011,
        2012,
        2013,
        2014,
        2015,
        2016,
        2017,
        "2018*",
      ],
      datasets: [
        {
          type: "bar",
          label: "Nombre annuel de données",
          data: [
            36,
            42,
            34,
            103,
            155,
            261,
            548,
            832,
            2387,
            4395,
            4321,
            4478,
            5135,
            5002,
            5870,
          ],
          backgroundColor: randomColorGenerator(5),
          borderColor: "grey",
          borderWidth: 1,
        },
        {
          type: "line",
          label: "Nombre cumulé de données",
          data: [
            36,
            78,
            112,
            215,
            370,
            631,
            1179,
            2011,
            4398,
            8793,
            13114,
            17592,
            22727,
            27729,
            33599,
          ],
          backgroundColor: randomColorGenerator(5),
        },
      ],
    },
    options: {
      legend: {
        display: true,
        usePointStyle: true,
      },
      scales: {
        yAxes: [
          {
            ticks: {
              beginAtZero: true,
            },
          },
        ],
      },
      title: {
        display: true,
        text: "Nombre de données au cours des 15 dernières années",
      },
      responsive: true,
      maintainAspectRatio: false,
    },
  });

  const NbDataMortaMois = document.getElementById("NbDataMortaMoisGraph");
  const NbDataMortaMoisChart = new Chart(NbDataMortaMois, {
    type: "line",
    data: {
      labels: [
        "janv.",
        "fév.",
        "mars",
        "avril",
        "mai",
        "juin",
        "juillet",
        "août",
        "sept.",
        "oct.",
        "nov.",
        "déc.",
      ],
      datasets: [
        {
          label: "Nombre de données",
          data: [
            1332,
            2004,
            4665,
            4689,
            3552,
            3623,
            3219,
            2864,
            2772,
            2419,
            1572,
            1113,
          ],
          // backgroundColor: 'rgba(52, 124, 204,0.7)'
          backgroundColor: randomColorGenerator(5),
        },
      ],
    },
    options: {
      legend: {
        display: false,
      },
      scales: {
        yAxes: [
          {
            ticks: {
              beginAtZero: true,
            },
          },
        ],
      },
      title: {
        display: true,
        text: "Nombre de données de mortalité par mois",
      },
      label: {
        display: true,
      },
      responsive: true,
      maintainAspectRatio: false,
    },
  });

  const NbDataMortaDecadeGrp = document.getElementById(
    "NbDataMortaDecadeGrpGraph",
  );
  const NbDataMortaDecadeGrpChart = new Chart(NbDataMortaDecadeGrp, {
    type: "bar",
    data: {
      labels: [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30,
        31,
        32,
        33,
        34,
        35,
        36,
      ],
      datasets: [
        {
          type: "line",
          label: "Reptiles",
          data: [
            4,
            1,
            3,
            null,
            2,
            2,
            7,
            14,
            21,
            65,
            96,
            137,
            146,
            171,
            253,
            218,
            204,
            167,
            139,
            113,
            97,
            78,
            77,
            106,
            82,
            94,
            82,
            66,
            39,
            43,
            22,
            10,
            1,
            1,
            3,
            4,
            1,
          ],
          backgroundColor: randomColorGenerator(5),
        },
        {
          type: "line",
          label: "Oiseaux",
          data: [
            120,
            87,
            140,
            143,
            147,
            181,
            228,
            270,
            218,
            252,
            239,
            188,
            165,
            179,
            185,
            178,
            176,
            176,
            172,
            164,
            148,
            147,
            111,
            132,
            144,
            136,
            119,
            118,
            105,
            160,
            123,
            96,
            100,
            129,
            128,
            76,
            59,
          ],
          backgroundColor: randomColorGenerator(5),
        },
        {
          type: "line",
          label: "Mammifères",
          data: [
            234,
            269,
            282,
            337,
            391,
            485,
            514,
            713,
            911,
            1193,
            1113,
            820,
            639,
            710,
            756,
            765,
            787,
            833,
            773,
            794,
            685,
            713,
            621,
            693,
            687,
            684,
            592,
            546,
            504,
            475,
            371,
            352,
            307,
            288,
            254,
            196,
            121,
          ],
          backgroundColor: randomColorGenerator(5),
        },
        {
          type: "line",
          label: "Amphibiens",
          data: [
            34,
            26,
            23,
            48,
            110,
            255,
            445,
            533,
            578,
            363,
            178,
            153,
            106,
            71,
            49,
            42,
            36,
            25,
            31,
            33,
            28,
            33,
            29,
            39,
            39,
            90,
            66,
            111,
            127,
            121,
            128,
            93,
            64,
            45,
            23,
            26,
            7,
          ],
          backgroundColor: randomColorGenerator(5),
        },
      ],
    },
    options: {
      legend: {
        display: true,
        usePointStyle: true,
        labels: {
          boxWidth: 12,
        },
      },
      scales: {
        yAxes: [
          {
            ticks: {
              beginAtZero: true,
            },
          },
        ],
      },
      title: {
        display: true,
        text: "Nombre de données par groupes d'espèces et par décades",
      },
      responsive: true,
      maintainAspectRatio: false,
    },
  });

  const NbDataMortaEsp = document.getElementById("NbDataMortaEspGraph");
  const NbDataMortaEspChart = new Chart(NbDataMortaEsp, {
    type: "bar",
    data: {
      labels: [
        "Hérisson d'Europe",
        "Blaireau européen",
        "Renard roux",
        "Ecureuil roux",
        "Crapaud commun ou épineux",
        "Fouine",
        "Salamandre tachetée",
        "Merle noir",
        "Martre des pins",
        "Martre / Fouine",
      ],
      datasets: [
        {
          label: "Nombre de données de mortalité",
          data: [6535, 3212, 2577, 1986, 1981, 1310, 1022, 944, 831, 816],
          backgroundColor: [
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
          ],
          borderColor: "grey",
          borderWidth: 1,
        },
      ],
    },
    options: {
      legend: {
        display: false,
        labels: {
          boxWidth: 12,
        },
      },
      title: {
        display: true,
        text: "Nombre de données pour les 10 taxons les plus observées",
      },
      scaleShowLabels: false,
      labelAlign: "center",
      animateRotate: true,
      animateScale: false,
      responsive: true,
      maintainAspectRatio: false,
    },
  });
  const NbDataMortaPatEsp = document.getElementById("NbDataMortaEspPatGraph");
  const NbDataMortaPatEspChart = new Chart(NbDataMortaPatEsp, {
    type: "bar",
    data: {
      labels: [
        "Effraie des clochers",
        "Lapin de garenne",
        "Putois d'Europe",
        "Chevêche d'Athéna",
        "Grand-duc d'Europe",
        "Castor d'Eurasie",
        "Perdrix rouge",
        "Triton alpestre",
        "Loutre d'Europe",
        "Pie-grièche écorcheur",
      ],
      datasets: [
        {
          label: "Nombre de données de mortalité",
          data: [616, 488, 334, 150, 84, 76, 52, 43, 42, 29],
          backgroundColor: [
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
            randomColorGenerator(5),
          ],
          borderColor: "grey",
          borderWidth: 1,
        },
      ],
    },
    options: {
      legend: {
        display: false,
        labels: {
          boxWidth: 12,
        },
      },
      title: {
        display: true,
        text:
          "Nombre de données pour les 10 espèces patrimoniales* les plus observées",
      },
      scaleShowLabels: false,
      labelAlign: "center",
      animateRotate: true,
      animateScale: false,
      responsive: true,
      maintainAspectRatio: false,
    },
  });
  const NbObserverEspMort = document.getElementById("NbObserverEspMortGraph");
  const NbObserverEspMortChart = new Chart(NbObserverEspMort, {
    type: "bar",
    data: {
      labels: [
        2004,
        2005,
        2006,
        2007,
        2008,
        2009,
        2010,
        2011,
        2012,
        2013,
        2014,
        2015,
        2016,
        2017,
        "2018*",
      ],
      datasets: [
        {
          data: [
            17,
            15,
            12,
            28,
            31,
            53,
            92,
            123,
            336,
            451,
            479,
            504,
            535,
            568,
            589,
          ],
          backgroundColor: randomColorGenerator(5),
          borderColor: "grey",
          borderWidth: 1,
        },
      ],
    },
    options: {
      legend: {
        display: false,
        labels: {
          boxWidth: 12,
        },
      },
      title: {
        display: true,
        text:
          "Nombre d'observateurs actifs (saisie de données de mortalité) par années",
      },
      scaleShowLabels: false,
      labelAlign: "center",
      animateRotate: true,
      animateScale: false,
      responsive: true,
      maintainAspectRatio: false,
    },
  });
};
